# This file was generated by GoReleaser. DO NOT EDIT.
cask "cinzel" do
  name "cinzel"
  desc "Bidirectional converter between HCL and CI/CD YAML"
  homepage "https://github.com/yldio/cinzel"
  version "0.0.8"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cinzel"

  on_macos do
    on_intel do
      url "https://github.com/yldio/cinzel/releases/download/v#{version}/cinzel_#{version}_darwin_amd64.tar.gz"
      sha256 "9297bb3ce38d0d814372301f2bde8aa2f15d2da2aaafb3e0bc8834d23537313d"
    end
    on_arm do
      url "https://github.com/yldio/cinzel/releases/download/v#{version}/cinzel_#{version}_darwin_arm64.tar.gz"
      sha256 "618e1622294420b474d5de6042172f96a3925580cf7fd6751e9790a5e920cd85"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/yldio/cinzel/releases/download/v#{version}/cinzel_#{version}_linux_amd64.tar.gz"
      sha256 "ec22501a7d6fc3b1a31cb8cb3934435f37f89355a392da88e1c8fc24b9203df1"
    end
    on_arm do
      url "https://github.com/yldio/cinzel/releases/download/v#{version}/cinzel_#{version}_linux_arm64.tar.gz"
      sha256 "8372e0b4845410ad2b8fa3959a83092d9bab22243b8f74d3a89195faf155121e"
    end
  end

  # No zap stanza required
end
