# This file was generated by GoReleaser. DO NOT EDIT.
cask "cinzel" do
  name "cinzel"
  desc "Bidirectional converter between HCL and CI/CD YAML"
  homepage "https://github.com/yldio/cinzel"
  version "0.5.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cinzel"

  on_macos do
    on_intel do
      url "https://github.com/yldio/cinzel/releases/download/v#{version}/cinzel_#{version}_darwin_amd64.tar.gz"
      sha256 "3dad84310e26b9efeb0f091a4f84882618cb4b5757865ca4b1d6e768daff022c"
    end
    on_arm do
      url "https://github.com/yldio/cinzel/releases/download/v#{version}/cinzel_#{version}_darwin_arm64.tar.gz"
      sha256 "987493bc3c465f6b3654768dd074ee3816256dc6589fc266bc70c082c22dbdfe"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/yldio/cinzel/releases/download/v#{version}/cinzel_#{version}_linux_amd64.tar.gz"
      sha256 "a7ab007650cd1a0621c22e851d40cc15ce8b11a637caaefe8bc4a9dd0ef44581"
    end
    on_arm do
      url "https://github.com/yldio/cinzel/releases/download/v#{version}/cinzel_#{version}_linux_arm64.tar.gz"
      sha256 "687107f3054320d5ddaac7a4725ecdb21b0ca1ca7d831121df000319b680ceff"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cinzel"]
    end
  end

  # No zap stanza required
end
