# This file was generated by GoReleaser. DO NOT EDIT.
cask "cinzel" do
  name "cinzel"
  desc "Bidirectional converter between HCL and CI/CD YAML"
  homepage "https://github.com/yldio/cinzel"
  version "0.3.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cinzel"

  on_macos do
    on_intel do
      url "https://github.com/yldio/cinzel/releases/download/v#{version}/cinzel_#{version}_darwin_amd64.tar.gz"
      sha256 "9a957a59b41094a2b155f612960802c9e2df8d07c8bdb3074482c1e9058ce4b7"
    end
    on_arm do
      url "https://github.com/yldio/cinzel/releases/download/v#{version}/cinzel_#{version}_darwin_arm64.tar.gz"
      sha256 "8f910d9fbd00d624fcf8a74c74fa6f1de32e77d2be631c86bc4cdf004bd3a008"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/yldio/cinzel/releases/download/v#{version}/cinzel_#{version}_linux_amd64.tar.gz"
      sha256 "71fefe0537754928157433f107f684c2fa43abce69229ffd86565ebb63ebdaa2"
    end
    on_arm do
      url "https://github.com/yldio/cinzel/releases/download/v#{version}/cinzel_#{version}_linux_arm64.tar.gz"
      sha256 "b1ddb93510736360fe8a64a3b74e2640a86a4ba565b01debcae07b12933c5aa5"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cinzel"]
    end
  end

  # No zap stanza required
end
